const fs = require('fs')
const path = require('path')

exports.default = async function(context) {
  // Path to the node_modules generated by Next.js standalone build
  const src = path.join(context.packager.projectDir, '.next', 'standalone', 'node_modules')
  
  // Path to where extraResources places the standalone folder inside the unpacked app
  const dest = path.join(context.appOutDir, 'resources', 'standalone', 'node_modules')
  
  if (fs.existsSync(src)) {
    console.log(`\n📦 [afterPack] Copying standalone node_modules to packaged resources...`)
    fs.cpSync(src, dest, { recursive: true })
    console.log(`✅ [afterPack] Copied node_modules successfully!`)
  } else {
    console.warn(`⚠️ [afterPack] Source node_modules not found at ${src}`)
  }
}
